server:
  port: 8003

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

spring:
  cloud:
    gateway:
      routes:
        - id: api-gateway
          uri: http://localhost:8002
          predicates:
            - Path=/api/**

dubbo:
  application:
    name: dubbo-springboot-demo-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

